#baseurl = "https://zhaohuabing.com"
baseurl = "https://webb-blog.com"
title = "Webb Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
enableEmoji = true
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = "UA-147993035-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/backdrop.jpg"
  SEOTitle = " A blog for the web"
  description = "A blog about me and the things I like."
  keyword = "Kyle Webb, Webb, Blog"
  # customCSS = ["custom.css"]
  image_404 = "img/404-bg.jpg"
  title_404 = "You've lost you're way :("

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Data scientist, Liverpool fanatic, Investigator, Husband, Son"
  sidebar_avatar = "img/profile.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 0
  
  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = false
  bookmarks = true
  about_me = false

  [params.social]
  rss            = true 
  email          = "webb.kyle@outlook.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/webbkyle"
  #wechat         = "your wechat qr code image"
  #medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"
  
  [[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title =  "David Brooks"
  href =  "https://www.nytimes.com/column/david-brooks"
  [[params.bookmark_link]]
  title = "Andrew Gelman"
  href =  "https://statmodeling.stat.columbia.edu/"
  [[params.bookmark_link]]
  title =  "538"
  href = "https://fivethirtyeight.com/"
  [[params.bookmark_link]]
  title = "Ross Douthat"
  href = "https://www.nytimes.com/column/ross-douthat"
  
  
  [[params.addtional_menus]]
  #title =  "Links"
  #href =  "/top/links/"
  [[params.addtional_menus]]
  #title =  "Resume"
  #href =  "/top/resume/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 
