---
title: NCAA March Madness - 2020
author: Kyle Webb
date: '2019-09-17'
slug: ncaa-march-madness-2020
categories:
  - data science
  - sports
tags: [data science, sports]
subtitle: ''
description: 'How I built my brackets and how they eventually BUSTED'
image: ''
draft: true
output:
  blogdown::html_page:
    toc: true
---

Ah March... the birds are back (both motorized and natural), the weather is (a tiny bit) warmer, and 68 collegiate teams hash out their skills in an all-out, maddening basketball do-or-die nation-wide tournament. March is back baby!

I love NCAA March Madness. Although I never really watch college basketball through the regular season, I find the tournament too thrilling to ignore. Given that I have no understanding of most of the teams when the tourney starts, I have to rely on data and modeling techniques to make *some* sort of educated guesses. I tried last year to model tournament games, but with only two days left until submission for my brackets, I was pushed to exhaustion and eventually ended up just copying someone's code from Kaggle. I knew that this year I would need to step up my game in terms of preperation - *especially* in terms of data collection and cleaning. 

#### Data

This year, I used data from [Kenpom](https://kenpom.com/). The tourney games that I used went as far back as 2002. The teams in this dataset include all D-1 collegiate basketball teams so I ended up having to grab tourney teams that had appointed seeds. I then found matchups for these teams  

#### Models

This will be about models.

#### Results

This will be about results.

#### Conclusions

This will be about conclusions.


